<?php


namespace app\base;


use yii\base\Action;

class BaseAction extends Action
{

    public function beforeRun()
    {

        return parent::beforeRun(); // TODO: Change the autogenerated stub
    }

    public function afterRun()
    {
        parent::afterRun(); // TODO: Change the autogenerated stub
    }

}